import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "Legal disclaimer for Probatio audio similarity analysis platform.",
};

export default function DisclaimerPage() {
  return (
    <div className="bg-obsidian min-h-screen">
      <article className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="font-display text-4xl text-bone mb-2">Disclaimer</h1>
        <p className="text-xs text-ash/60 mb-8">
          Document ID: PROBATIO-DISC-001 &middot; Last Updated: March 2026
        </p>

        <div className="space-y-6 text-ash leading-relaxed">
          <p>
            Probatio is an analytical tool that provides quantitative
            measurements of audio similarity. Probatio does not provide legal
            advice, legal opinions, or determinations of copyright
            infringement.
          </p>

          <p>
            Similarity scores, risk classifications, and forensic reports
            generated by Probatio are technical findings based on signal
            processing and machine learning algorithms. They do not constitute
            legal conclusions and should not be treated as such.
          </p>

          <p>
            Legal conclusions &mdash; including determinations of substantial
            similarity, access, and infringement &mdash; are within the
            exclusive purview of courts and qualified legal professionals.
          </p>

          <p>
            Users should consult qualified legal counsel before making
            decisions based on Probatio&apos;s analysis results. This is
            especially important before sending cease-and-desist letters,
            filing lawsuits, or making public allegations of copying.
          </p>

          <div className="border-t border-slate pt-6 mt-8">
            <h2 className="font-display text-xl text-bone mb-4">
              Technical Limitations
            </h2>
            <ul className="list-disc list-inside space-y-2 text-sm">
              <li>
                Audio quality degradation (compression, noise, transcoding)
                may affect the accuracy of results
              </li>
              <li>
                Common musical patterns (standard chord progressions,
                idiomatic phrases) may produce elevated similarity scores that
                do not indicate copying
              </li>
              <li>
                The system analyzes recorded audio signals, not musical
                notation, compositional intent, or lyrical content
              </li>
              <li>
                The reference catalog, while extensive, does not represent all
                copyrighted works globally
              </li>
              <li>
                Short audio segments (&lt;4 seconds) may have insufficient
                data for reliable comparison
              </li>
            </ul>
          </div>

          <div className="border-t border-slate pt-6 mt-8">
            <h2 className="font-display text-xl text-bone mb-4">
              Forensic Analysis
            </h2>
            <p>
              Forensic analysis reports are designed to support, not replace,
              proper legal evidence procedures. The methodology is designed to
              meet Daubert standard requirements for scientific evidence, but
              admissibility is determined by the presiding court based on the
              applicable rules of evidence and the specific circumstances of
              the case.
            </p>
            <p className="mt-4">
              Chain of custody integrity can be independently verified using
              the SHA-256 hash chain provided with each analysis. Users and
              their legal counsel are responsible for ensuring evidence is
              properly introduced in accordance with applicable procedural
              rules.
            </p>
          </div>
        </div>

        <div className="mt-12 pt-6 border-t border-slate">
          <p className="text-xs text-ash/50">
            Clandestino Ventures, LLC &copy; 2026. Document version 1.0.0.
          </p>
        </div>
      </article>
    </div>
  );
}
