/**
 * PROBATIO — Screening Report Template
 *
 * Defines the structure and generation logic for standard screening
 * analysis reports. These reports summarize similarity findings,
 * risk assessment, and recommendations for a user's uploaded track.
 */

import { PIPELINE_VERSION, APP_NAME, SUPPORT_EMAIL } from "@/lib/constants";
import { THRESHOLD_VERSION, getRecommendation } from "@/lib/analysis/risk-classifier";
import type { RiskLevel, AnalysisRow, AnalysisMatchRow, ReferenceTrackRow } from "@/types/database";
import type { SimilarityScore } from "@/types/analysis";

// ────────────────────────────────────────────────────────────────────────────
// Report Structure
// ────────────────────────────────────────────────────────────────────────────

/** Header section with report and analysis metadata. */
export interface ScreeningReportHeader {
  reportId: string;
  title: string;
  generatedAt: string;
  analysisId: string;
  analysisMode: string;
  pipelineVersion: string;
  thresholdVersion: string;
  platform: string;
}

/** Summary of the uploaded track. */
export interface ScreeningTrackSummary {
  fileName: string;
  fileSizeBytes: number;
  durationSeconds: number | null;
  fileHash: string;
  /** Audio metadata derived from normalization_metrics JSONB, if available. */
  audioMeta: {
    sampleRate: number | null;
    channels: number | null;
    format: string | null;
  } | null;
}

/** A single match entry in the screening report. */
export interface ScreeningMatchEntry {
  rank: number;
  referenceTitle: string;
  referenceArtist: string;
  referenceAlbum: string | null;
  isrc: string | null;
  scores: SimilarityScore;
  riskLevel: RiskLevel;
  confidence: number;
  matchedSegmentCount: number;
  /** Top matched segments (limited to 5 for readability). */
  topSegments: ScreeningSegmentEntry[];
}

/** A matched segment within a screening match entry. */
export interface ScreeningSegmentEntry {
  queryStartSeconds: number;
  queryEndSeconds: number;
  referenceStartSeconds: number;
  referenceEndSeconds: number;
  similarity: number;
  dominantDimension: string;
}

/** Overall risk assessment section. */
export interface ScreeningRiskAssessment {
  overallRisk: RiskLevel;
  label: string;
  description: string;
  recommendations: readonly string[];
  totalMatchesFound: number;
  highRiskMatchCount: number;
  criticalRiskMatchCount: number;
}

/** The complete screening report. */
export interface ScreeningReport {
  header: ScreeningReportHeader;
  trackSummary: ScreeningTrackSummary;
  riskAssessment: ScreeningRiskAssessment;
  matches: ScreeningMatchEntry[];
  disclaimer: string;
}

// ────────────────────────────────────────────────────────────────────────────
// Max entries in report
// ────────────────────────────────────────────────────────────────────────────

/** Maximum number of matches to include in the report. */
const MAX_MATCHES_IN_REPORT = 20;

/** Maximum number of segments per match to include. */
const MAX_SEGMENTS_PER_MATCH = 5;

// ────────────────────────────────────────────────────────────────────────────
// Disclaimer
// ────────────────────────────────────────────────────────────────────────────

const REPORT_DISCLAIMER =
  `This report was generated by ${APP_NAME} using automated audio analysis algorithms ` +
  `(pipeline v${PIPELINE_VERSION}, thresholds v${THRESHOLD_VERSION}). ` +
  "It is intended as an informational tool and does not constitute legal advice. " +
  "Similarity scores reflect algorithmic analysis and may not correspond to legal " +
  "determinations of copyright infringement. Consult a qualified music copyright " +
  `attorney for legal guidance. Contact: ${SUPPORT_EMAIL}`;

// ────────────────────────────────────────────────────────────────────────────
// Report Generation
// ────────────────────────────────────────────────────────────────────────────

export interface GenerateScreeningReportInput {
  analysis: AnalysisRow;
  matches: AnalysisMatchRow[];
  referenceTracks: Map<string, ReferenceTrackRow>;
}

/**
 * Generate a complete screening report from analysis data.
 *
 * @param input  Analysis record, matches, and reference track data.
 * @returns A fully populated {@link ScreeningReport}.
 */
export function generateScreeningReport(
  input: GenerateScreeningReportInput,
): ScreeningReport {
  const { analysis, matches, referenceTracks } = input;

  // ── Header ─────────────────────────────────────────────────────────────
  const header: ScreeningReportHeader = {
    reportId: crypto.randomUUID(),
    title: `Screening Report: ${analysis.file_name}`,
    generatedAt: new Date().toISOString(),
    analysisId: analysis.id,
    analysisMode: analysis.mode,
    pipelineVersion: analysis.pipeline_version ?? PIPELINE_VERSION,
    thresholdVersion: THRESHOLD_VERSION,
    platform: APP_NAME,
  };

  // ── Track Summary ──────────────────────────────────────────────────────
  const normMetrics = analysis.normalization_metrics as Record<string, unknown> | null;
  const preMeta = normMetrics?.pre as Record<string, unknown> | null | undefined;
  const trackSummary: ScreeningTrackSummary = {
    fileName: analysis.file_name,
    fileSizeBytes: analysis.file_size_bytes,
    durationSeconds: analysis.duration_seconds,
    fileHash: analysis.file_hash,
    audioMeta: preMeta
      ? {
          sampleRate: (preMeta.sampleRate as number) ?? null,
          channels: (preMeta.channels as number) ?? null,
          format: (preMeta.format as string) ?? null,
        }
      : null,
  };

  // ── Matches ────────────────────────────────────────────────────────────
  // Sort matches by overall score descending (highest risk first).
  const sortedMatches = [...matches].sort(
    (a, b) => (b.score_overall ?? 0) - (a.score_overall ?? 0),
  );

  const matchEntries: ScreeningMatchEntry[] = sortedMatches
    .slice(0, MAX_MATCHES_IN_REPORT)
    .map((match, index) => {
      const refTrack = referenceTracks.get(match.reference_track_id);
      const segments = (match.timestamps_similarity || []) as Record<string, unknown>[];

      const topSegments: ScreeningSegmentEntry[] = segments
        .slice(0, MAX_SEGMENTS_PER_MATCH)
        .map((seg) => ({
          queryStartSeconds: seg.queryStart as number ?? 0,
          queryEndSeconds: seg.queryEnd as number ?? 0,
          referenceStartSeconds: seg.referenceStart as number ?? 0,
          referenceEndSeconds: seg.referenceEnd as number ?? 0,
          similarity: seg.similarity as number ?? 0,
          dominantDimension: seg.dominantDimension as string ?? "melody",
        }));

      return {
        rank: index + 1,
        referenceTitle: refTrack?.title ?? "Unknown Track",
        referenceArtist: refTrack?.artist ?? "Unknown Artist",
        referenceAlbum: refTrack?.album ?? null,
        isrc: refTrack?.isrc ?? null,
        scores: {
          melody: match.score_melody ?? 0,
          harmony: match.score_harmony ?? 0,
          rhythm: match.score_rhythm ?? 0,
          structure: match.score_timbre ?? 0,
          overall: match.score_overall ?? 0,
        },
        riskLevel: match.risk_level,
        confidence: match.overall_similarity,
        matchedSegmentCount: segments.length,
        topSegments,
      };
    });

  // ── Risk Assessment ────────────────────────────────────────────────────
  const overallRisk = analysis.overall_risk ?? "low";
  const recommendation = getRecommendation(overallRisk);

  const highRiskCount = matches.filter(
    (m) => m.risk_level === "high" || m.risk_level === "critical",
  ).length;

  const criticalRiskCount = matches.filter(
    (m) => m.risk_level === "critical",
  ).length;

  const riskAssessment: ScreeningRiskAssessment = {
    overallRisk,
    label: recommendation.label,
    description: recommendation.description,
    recommendations: recommendation.actions,
    totalMatchesFound: matches.length,
    highRiskMatchCount: highRiskCount,
    criticalRiskMatchCount: criticalRiskCount,
  };

  return {
    header,
    trackSummary,
    riskAssessment,
    matches: matchEntries,
    disclaimer: REPORT_DISCLAIMER,
  };
}
